version: "1"
services:
    frontend-rt:
        build:
            context: ./frontend
        ports:
            - "3000:3000"

    backend-rt:
        build:
            context: ./backend
        ports:
            - "8080:8080"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
